# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\李展旗\Desktop\ceshi\down_img.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(803, 441)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 120, 341, 311))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 70, 141, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 210, 254);\n"
"border-radius:4px;\n"
"font: 14pt \"幼圆\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 70, 131, 41))
        self.label.setStyleSheet("font: 14pt \"幼圆\";")
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(430, 100, 381, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(430, 60, 161, 41))
        self.label_2.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(140, 20, 661, 36))
        self.lineEdit.setStyleSheet("background-color:rgb(229, 237, 255);\n"
"border-radius: 10px;\n"
"font: 14pt \"幼圆\";")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 111, 51))
        self.label_3.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 70, 71, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 210, 254);\n"
"border-radius:4px;\n"
"font: 14pt \"幼圆\";")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "爬秒应"))
        self.pushButton.setText(_translate("Form", "开始"))
        self.label.setText(_translate("Form", "登录二维码"))
        self.label_2.setText(_translate("Form", "输出信息"))
        self.label_3.setText(_translate("Form", "作业链接"))
        self.pushButton_2.setText(_translate("Form", "登录"))
