# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\李展旗\Desktop\ceshi\put.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(893, 386)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(5, 171, 311, 211))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(335, 170, 311, 211))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(510, 90, 131, 61))
        self.pushButton.setStyleSheet("background-color: rgb(255, 210, 254);\n"
"border-radius:4px;\n"
"font: 14pt \"幼圆\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 90, 131, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 210, 254);\n"
"border-radius:4px;\n"
"font: 14pt \"幼圆\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(590, 0, 111, 41))
        self.label.setStyleSheet("font: 14pt \"幼圆\";")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(340, 90, 151, 51))
        self.comboBox.setStyleSheet("font: 16pt \"幼圆\";")
        self.comboBox.setObjectName("comboBox")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(670, 0, 221, 381))
        self.listWidget.setStyleSheet("font: 10pt \"幼圆\";")
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "提交页面"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.pushButton_2.setText(_translate("Form", "选择文件"))
        self.label.setText(_translate("Form", "信息"))
