# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\李展旗\Desktop\ceshi\sum_img_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(954, 385)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 180, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(320, 180, 256, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(680, 180, 256, 192))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(800, 40, 131, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 210, 254);\n"
"border-radius:4px;\n"
"font: 14pt \"幼圆\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(640, 40, 151, 51))
        self.comboBox.setStyleSheet("font: 16pt \"幼圆\";")
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 230, 81, 91))
        self.label.setStyleSheet("font: 60pt \"幼圆\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(600, 220, 81, 91))
        self.label_2.setStyleSheet("font: 60pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 100, 131, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 210, 254);\n"
"border-radius:4px;\n"
"font: 14pt \"幼圆\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 100, 131, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 210, 254);\n"
"border-radius:4px;\n"
"font: 14pt \"幼圆\";")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图片合成"))
        self.pushButton_2.setText(_translate("Form", "合成"))
        self.label.setText(_translate("Form", "+"))
        self.label_2.setText(_translate("Form", "="))
        self.pushButton_3.setText(_translate("Form", "打开"))
        self.pushButton_4.setText(_translate("Form", "打开"))
